apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: online-event-booking-sarib-aftab
  labels:
    app: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: event-booking/booking-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: BOOKING_SERVICE_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: NODE_ENV
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: event-booking-secrets
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: event-booking-secrets
              key: SUPABASE_KEY
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)"
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: event-booking-secrets
              key: RABBITMQ_PASSWORD
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: USER_SERVICE_URL
        - name: EVENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: EVENT_SERVICE_URL
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: online-event-booking-sarib-aftab
spec:
  selector:
    app: booking-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP
