apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: online-event-booking-sarib-aftab
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: event-booking/user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "0.75"
            memory: "1Gi"
          requests:
            cpu: "0.3"
            memory: "512Mi"
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: USER_SERVICE_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: event-booking-config
              key: NODE_ENV
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: event-booking-secrets
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: event-booking-secrets
              key: SUPABASE_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: event-booking-secrets
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: online-event-booking-sarib-aftab
spec:
  selector:
    app: user-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 
