apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-booking-ingress
  namespace: online-event-booking-sarib-aftab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Enable SSL redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Optional: Add TLS configuration 
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  # Optional: Configure TLS
  # tls:
  # - hosts:
  #   - event-booking.example.com
  #   secretName: event-booking-tls
  rules:
  - host: event-booking.example.com  # Replace with your actual domain
    http:
      paths:
      # Frontend routes
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
              
      # User Service API
      - path: /api/users(.*)
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 3001
              
      # Event Service API
      - path: /api/events(.*)
        pathType: Prefix
        backend:
          service:
            name: event-service
            port:
              number: 3002
              
      # Booking Service API
      - path: /api/bookings(.*)
        pathType: Prefix
        backend:
          service:
            name: booking-service
            port:
              number: 3003
              
      # Notification Service API
      - path: /api/notifications(.*)
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 3004 
