apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  registries.yaml: |
    mirrors:
      "localhost:5000":
        endpoint:
          - "http://localhost:5000"
    configs:
      "localhost:5000":
        tls:
          insecure_skip_verify: true 