apiVersion: v1
kind: Secret
metadata:
  name: event-booking-secrets
  namespace: online-event-booking-sarib-aftab
type: Opaque
data:
  # These are base64 encoded values from your .env files
  JWT_SECRET: dEJyMmtEbEJDTzF4dUNDNGNsQm00VU9QMUJCVGJ6ZG81Z0t3aVV1Z3JQVzh4VytyNFkydGRTM3MrSVJWMUt2WWoxZC9FN2lZLzJsaTVXS0tMeXNZTXc9PQ==
  SUPABASE_URL: aHR0cHM6Ly96YmN4d2ZhY3Rrc2hrYmdzbW9sZi5zdXBhYmFzZS5jbw==
  SUPABASE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5waVkzaDNabUZqZEd0emFHdGlaM050YjJ4bUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTkRBNU5ETTFNVEFzSW1WNGNDSTZNakExTmpVeE9UVXhNSDAuMnF2VkgzYTJmQS1EbEFuQ2lqMUZsMkdDMnNwR2g5S2tnZUI2R19pdV9Z
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9TYXJpYjpNb25nb2RiMTIzJTQwQGV2ZW50LWJvb2tpbmcucWNibm0ubW9uZ29kYi5uZXQvZXZlbnQtYm9va2luZz9yZXRyeVdyaXRlcw==
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  EMAIL_PASSWORD: cmdpcnVyemx5bWd4eWlqeA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: online-event-booking-sarib-aftab
type: Opaque
data:
  username: U2FyaWI=
  password: TW9uZ29kYjEyMyU0MA== 
